cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'ansible'
brew 'coreutils'
brew 'composer'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'mysql'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'phpunit'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 'spaceman-diff'
brew 'spark'
brew 'unrar'
brew 'wget'
brew 'wp-cli'
brew 'yarn'
brew 'youtube-dl'

cask 'betterzipql'
cask 'caffeine'
cask 'calibre'
cask 'cheatsheet'
cask 'fontprep'
cask 'handbrake'
cask 'imageoptim'
cask 'qlcolorcode'
cask 'qlimagesize'
cask 'qlmarkdown'
cask 'qlstephen'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'the-unarchiver'
cask 'torbrowser'
cask 'vlc'
cask 'xquartz'

